### ISSUE TITLE
Drupal chapter

### ISSUE THREAD

**Issue by Haru0** [Selectra-Dev/standards#16]
Do we have any specific standards for Drupal applications? Could we put sub-chapter or maybe we need a separate file for it?

**Comment by jorgecar** [comment]
Nothing personal, everything I do I try that this on the lines that are explained in Drupal.org

User Guide:
https://www.drupal.org/docs/user_guide/en/index.html

Documentation for developers:
https://www.drupal.org/docs/develop

Extending Drupal 8
https://www.drupal.org/docs/8/extending-drupal-8

**Comment by Haru0** [comment]
Don't you have any good practices, debugging guidelines etc.?

**Comment by Mexidense** [comment]
Hi @jorgecar 
Yep, Michał says any thing like: [PHP](https://github.com/Selectra-Dev/selectra-standards/blob/cleanup/programming/PHP.md) or [Laravel](https://github.com/Selectra-Dev/selectra-standards/blob/cleanup/programming/LARAVEL.md)

do you have any reference when you code? In a future, I would like to refactor selectra_directory module and I'd like to following any guidelines :smile: for my code smells :grin:

**Comment by jorgecar** [comment]
Yes, all of that you will be able to find in the first link: Documentation for developers:

Here, you will see for example: 
* Coding standards
https://www.drupal.org/docs/develop/standards/coding-standards

* Twig coding standards
https://www.drupal.org/docs/develop/coding-standards/twig-coding-standards
* SQL coding conventions

I mean, everything a developer needs to know.

In the other hand you have the Guide for Extending Drupal 8.

And, for your module, I think the appropriate would be improve the Services and dependency injection
https://www.drupal.org/docs/8/api/services-and-dependency-injection

**Comment by jorgecar** [comment]
let's just say it's super forbidden to have own conventions inside Drupal. It's a golden rule. And from Drupal.org they try to standardize as much as possible.

Other things are the particular workflows of our processes.

**Comment by jorgecar** [comment]
In fact in Drupal.org is standardized the use and configuration of working tools to ensure the use of standards and conventions of the framework. Examples:

* Configuring Visual Studio Code
https://www.drupal.org/docs/develop/development-tools/configuring-visual-studio-code

* Configuring Sublime Text
https://www.drupal.org/docs/develop/development-tools/configuring-sublime-text

Pick it up yourself:
https://www.drupal.org/docs/develop/development-tools

I've seen the PHP and Laravel documents and I haven't seen anything that hasn't been touched since the official Drupal documentation.

Maybe I can serve as a source of inspiration for PHP and Laravel documentation. Anything else, it will be a pleasure to guide you through the intricacies of Drupal.

**Comment by Mexidense** [comment]
Thank u for resources! I'll take in mind your suggestion about dependencies injection and services...

I just ask to you if you have any custom guidelines that uses for Selectra project :smile: but if you use same thing from Drupal community, it's good!

So, @Haru0 I think we can include a resource list with all links that @jorgecar gives us..

**Comment by Haru0** [comment]
Yup. Please put them in the separate chapter then. Thank you both!
